// src/components/header.jsx
import React from "react"
import styled from "styled-components"
import GithubIcon from "@images/github.svg"
import DownloadButton from "@images/download-button.svg"
import cvPDF from "@static/pdf/cv-alejandro-llorente.pdf"

const StyleHeader = styled.div`
  width: -webkit-fill-available;
  max-width: inherit;
  z-index: 999999;
`
const Actions = styled.div``

export const Header = () => (
  <StyleHeader className="bg-white h-8 fixed">
    <Actions className="flex justify-end items-center p-2">
      <a
        className="text-gray-600 ml-3"
        target="_blanck"
        href="https://github.com/ALLC84/cv"
      >
        <img className="w-5" src={GithubIcon} alt="icon github.svg" />
      </a>
      <a className="text-gray-600 ml-3" href={`${cvPDF}`} download>
        <img className="w-5" src={DownloadButton} alt="icon download" />
      </a>
    </Actions>
  </StyleHeader>
)

// src/components/sections/Header/index.vue
<template>
  <div class="actions">
    <a target="_blanck" href="https://github.com/ALLC84/cv">
      <img class="img" :src="GithubIcon" alt="icon github.svg" />
    </a>
    <a v-if="pdfToDownload" :href="pdfToDownload.url" target="_blanck" download>
      <img class="img" :src="DownloadButton" alt="icon download" />
    </a>
  </div>
</template>

<script>
import DownloadButton from '@/assets/images/download-button.svg';
import GithubIcon from '@/assets/images/github.svg';

import { request } from '../../../lib/datocms';

const QUERY = `
query {
  upload(filter: {id: {eq: "38903115"}}) {
    url
  }
}
`;

export default {
  name: 'Header',

  data() {
    return {
      DownloadButton,
      GithubIcon,
      pdfToDownload: null,
    };
  },

  mutation: {
    pdfDownload() {
      return this.pdfToDownload;
    },
  },

  async mounted() {
    await this.getContentData();
  },

  methods: {
    async getContentData() {
      try {
        const { upload } = await request({
          query: QUERY,
        });
        this.pdfToDownload = upload;
      } catch (e) {
        this.error = e;
      }
    },
  },
};
</script>

<style lang="scss" coped>
.actions {
  display: flex;
  justify-content: flex-end;

  .img {
    width: 1.3rem;
    margin-left: 0.8rem;
  }
}
</style>
