// src/components/sections/Aside/Avatar/index.vue
<template>
  <div class="wrapper__image">
    <img
      v-if="contact"
      class="image__avatar"
      :src="contact.photo.url"
      :alt="contact.photo.alt"
      width="200"
      height="200"
    />
  </div>
</template>
<script>
export default {
  name: 'Avatar',

  props: {
    contact: {
      type: Object,
      required: true,
    },
  },
};
</script>

<style lang="scss" scoped>
.wrapper__image {
  border: 2px solid #c4c4c4;
  border-radius: 100%;
  vertical-align: middle;
  margin: 0 auto;
  overflow: hidden;
  width: 200px;
  height: 200px;

  .image__avatar {
    max-width: 100%;
  }
}
</style>

// src/components/avatar.jsx
import React from 'react'
import Img from 'gatsby-image'
import styled from "styled-components"

import { useImageAvatar } from "@hooks"

const ImageContainer = styled.div`
  border: 2px solid #C4C4C4;
  border-radius: 100%;
  vertical-align: middle;
  width: 200px;
  height: 200px;
  margin: 15px auto 0 auto;
  overflow: hidden;
`

export const AvatarImage = () => {
  const image = useImageAvatar();

  return (
    <ImageContainer>
      <Img fluid={image.fluid} alt='Foto Alejandro Llorente'/>
    </ImageContainer>
  )

}
